[package]
name = "croftsoft-commander"
version = "0.1.0"
edition = "2021"
default-run = "commander"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "commander"
path = "src/lib.rs"

[[bin]]
name = "commander"
path = "src/main.rs"

[[bin]]
name = "commander-no-clap"
path = "src/main-no-clap.rs"

[dependencies]
clap = { version = "3", features = ["derive"] }
