# https://rust-lang.github.io/rustfmt/
array_width = 0
# group_imports = "StdExternalCrate"
# imports_layout = "HorizontalVertical"
max_width = 80
tab_spaces = 2
# version = "Two"
# wrap_comments = true
